library(tidyverse)
library(janitor)
bundibugyo <- read_csv("./Data/bundibugyo.csv")
tai <- read_csv("./Data/tai_forest.csv")
sudan <- read_csv("./Data/sudan.csv")
reston <- read_csv("./Data/reston.csv")
zaire1 <-read_csv("./Data/zaire_unknown.csv")
zaire2 <- read_csv("./Data/zaire_bat.csv")
zaire3 <- read_csv("./Data/zaire_chimp.csv")
  zaire4 <- read_csv("./Data/zaire_gorilla.csv")
  zaire5 <- read_csv("./Data/hum1.csv")
  zaire6 <- read_csv("./Data/hum2.csv")
  zaire7 <- read_csv("./Data/hum3.csv")
  zaire8 <- read_csv("./Data/hum4.csv")
  zaire9 <- read_csv("./Data/hum5.csv")
  zaire10 <- read_csv("./Data/hum7.csv")
ebola_data <- full_join(bundibugyo,tai)
ebola_data <- full_join(ebola_data, sudan)
ebola_data <- full_join(ebola_data, reston)
ebola_data <- full_join(ebola_data, zaire1)
ebola_data <- full_join(ebola_data, zaire2)
ebola_data <- full_join(ebola_data, zaire3)
ebola_data <- full_join(ebola_data, zaire4)
ebola_data <- full_join(ebola_data, zaire5)
ebola_data <- full_join(ebola_data, zaire6)
ebola_data <- full_join(ebola_data, zaire7)
ebola_data <- full_join(ebola_data, zaire8)
ebola_data <- full_join(ebola_data, zaire9)
ebola_data <- full_join(ebola_data, zaire10)

ebola_data <- ebola_data %>% clean_names()
ebola_data %>% names()
bundibugyo <- ebola_data %>% filter(str_detect(name, "Bundibugyo")) %>% mutate(type= "bundibugyo")
tai <- ebola_data %>% filter(str_detect(name, "Tai")) %>% mutate(type= "tai_forest")
sudan <- ebola_data %>% filter(str_detect(name, "Sudan")) %>% mutate(type= "sudan")
reston <- ebola_data %>% filter(str_detect(name, "Reston")) %>% mutate(type= "reston")
zaire <- ebola_data %>% filter(str_detect(name, "Zaire")) %>% mutate(type= "zaire")
df <- full_join(bundibugyo,tai)
df <- full_join(df, sudan)
df <- full_join(df, reston)
df <- full_join(df, zaire)
df <- df %>% select(-name) %>% mutate(strain=type) 
df <- df %>% select(-type)
df <- df %>% select(-c(release_date, accession))
write_csv(df, "./Data/ebola_strain_host_sample_type_cleaned.csv")
